spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: telegram-expense-bot

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:expenses}?tcpKeepAlive=true}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:paata_ai_business_bot}
    token: ${TELEGRAM_BOT_TOKEN}
groq:
  api-key: ${GROQ_API_KEY}
jina:
  api-key: ${JINA_API_KEY}
